### ISSUE TITLE
What is this place

### ISSUE THREAD

**Issue by a7hybnj2** [mraardvark/pymcuprog#1]
So, if this isn't the right place what is this repo for? Am I assuming correctly that pymcuprog is also your utility?

**Comment by mraardvark** [comment]
The wheel for pymcuprog is published on pypi: https://pypi.org/project/pymcuprog/
The source code (which is what this repo was setup for) is not being published right now...

**Comment by MCUdude** [comment]
> The source code (which is what this repo was setup for) is not being published right now...

Do you think the source code eventually will become open? Personally, I'm not a huge fan of command-line programs that's closed source. It's not that pymcuprog isn't good, It's just the feeling of "owning" your own tools that quite isn't there. 
Maybe I've just been too comfortable on my own little cloud where pretty much all my embedded tools (Arduino IDE, PlatformIO, avr-gcc, avr-libc, Avrdude etc.) are open source.

**Comment by mraardvark** [comment]
I do agree.
We plan to put it out early next year (some QA first).
Being python, the source is in the wheel already, so nothing to hide... Just some paperwork to be done first.

**Comment by MCUdude** [comment]
> I do agree.

Cool, I'm glad some of you MC guys still believe in open source. I've been a little worried where MC is heading with its AVR XC8 compiler and the fact that something has to be done to keep avr-gcc alive.

For me, personally, the reason why I love AVRs so much is transparency (and simplicity of course). Pretty much everything is open, including all my favorite tools (well, except the firmware for the official programmers, but that's too much to ask for I've heard).

**Comment by MCUdude** [comment]
@mraardvark Any updates on this? Would love to see the source code published!

**Comment by mraardvark** [comment]
With the weather we had over 'påskeferie' you might have expected everything to be published, right? :|
For this sprint the goal is to get pyedbglib out. If that goes well then pymcuprog is next.
Keep an eye out here: https://github.com/microchip-pic-avr-tools

**Comment by MCUdude** [comment]
I haven't been following the weather conditions in Trondheim, but here in Grenland, the weather has been exceptionally good the last few weeks.

I'll watch the microchip-pic-avr-tools page!

**Comment by mraardvark** [comment]
https://github.com/microchip-pic-avr-tools/pyedbglib/

**Comment by mraardvark** [comment]
https://github.com/microchip-pic-avr-tools/pymcuprog
